version: '3'

services:
  freqtrade_one:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_one
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_one.log
      --db-url sqlite:////freqtrade/user_data/freqtrade_one.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/kucoin-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-freqtrade_one.json
      --strategy Infinity