version: "3"

services:
  # Kucoin Stategies
  kucoin_1:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: kucoin_1
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/kucoin_1.log
      --db-url sqlite:////freqtrade/user_data/kucoin_1.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/kucoin-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-kucoin_1.json
      --strategy Infinity
    networks:
      - app-network

  kucoin_2:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: kucoin_2
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/kucoin_2.log
      --db-url sqlite:////freqtrade/user_data/kucoin_2.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/kucoin-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-kucoin_2.json
      --strategy NostalgiaForInfinityX
    networks:
      - app-network

  kucoin_3:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: kucoin_3
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/kucoin_3.log
      --db-url sqlite:////freqtrade/user_data/kucoin_3.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/kucoin-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-kucoin_3.json
      --strategy NASOS
    networks:
      - app-network

  # Binance Strategies
  binance_1:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: binance_1
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8083:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/binance_1.log
      --db-url sqlite:////freqtrade/user_data/binance_1.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/binance-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-binance_1.json
      --strategy Infinity
    networks:
      - app-network

  binance_2:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: binance_2
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8084:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/binance_2.log
      --db-url sqlite:////freqtrade/user_data/binance_2.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/binance-pairlist-volume-busd.json
      --config /freqtrade/user_data/config-binance_2.json
      --strategy NostalgiaForInfinityX
    networks:
      - app-network

  binance_3:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: binance_3
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8085:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/binance_3.log
      --db-url sqlite:////freqtrade/user_data/binance_3.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/binance-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-binance_3.json
      --strategy NASOS
    networks:
      - app-network
  
  exchange-proxy:
    image: mikekonan/exchange-proxy:latest-arm64
    restart: unless-stopped
    container_name: exchange-proxy
    command: -verbose 1
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
