version: "3"

services:
  freqtrade_one:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_one
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_one.log
      --db-url sqlite:////freqtrade/user_data/freqtrade_one.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/kucoin-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-freqtrade_one.json
      --strategy Infinity
    networks:
      - app-network

  freqtrade_two:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_two
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8081:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_two.log
      --db-url sqlite:////freqtrade/user_data/freqtrade_two.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/kucoin-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-freqtrade_two.json
      --strategy NostalgiaForInfinityX
    networks:
      - app-network

  freqtrade_three:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_three
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8082:8082"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_three.log
      --db-url sqlite:////freqtrade/user_data/freqtrade_three.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/binance-pairlist-volume-busd.json
      --config /freqtrade/user_data/config-freqtrade_three.json
      --strategy NostalgiaForInfinityX
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./views:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - freqtrade_one
      - freqtrade_two
      - freqtrade_three
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
