version: '3'

services:
  freqtrade:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/InfinityV7155.dryrun.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/binance-pairlist-volume-usdt.json
      --config /freqtrade/user_data/config-infinity.json
      --strategy InfinityV7155

  freqtrade2:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8081:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade2.log
      --db-url sqlite:////freqtrade/user_data/Mad.dryrun.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/binance-pairlist-busd.json
      --config /freqtrade/user_data/config-mad.json
      --strategy Mad

  freqtrade3:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade3
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8082:8082"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade3.log
      --db-url sqlite:////freqtrade/user_data/NASOSv4.dryrun.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/binance-pairlist-busd.json
      --config /freqtrade/user_data/config-NASOSv4.json
      --strategy NASOSv4
