version: '3'

services:
  freqtrade:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/ClucHAnix.dryrun.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/config-static.json
      --config /freqtrade/user_data/binance-pairlist.json
      --config /freqtrade/user_data/config-cluch-anix.json
      --strategy ClucHAnix

  freqtrade2:
    image: freqtrade:local
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8081:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/Mad.dryrun.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/config-static.json
      --config /freqtrade/user_data/binance-pairlist.json
      --config /freqtrade/user_data/config-mad.json
      --strategy Mad
